/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Medication = IDL.Record({
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
});
export const HealthData = IDL.Record({
  'meals' : IDL.Vec(IDL.Text),
  'waterIntake' : IDL.Nat,
  'medications' : IDL.Vec(Medication),
  'sleepHours' : IDL.Nat,
  'exerciseMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmergencyContacts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getHealthData' : IDL.Func([IDL.Principal], [HealthData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHealthData' : IDL.Func([HealthData], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Medication = IDL.Record({
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
  });
  const HealthData = IDL.Record({
    'meals' : IDL.Vec(IDL.Text),
    'waterIntake' : IDL.Nat,
    'medications' : IDL.Vec(Medication),
    'sleepHours' : IDL.Nat,
    'exerciseMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getHealthData' : IDL.Func([IDL.Principal], [HealthData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHealthData' : IDL.Func([HealthData], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };